apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle-adb
  namespace: oracle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-adb
  template:
    metadata:
      labels:
        app: oracle-adb
    spec:
      containers:
        - name: oracle-adb
          image: container-registry.oracle.com/database/adb-free:23.8.5.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/u01/app/oracle/oradata"
              name: oracle-adb
      volumes:
        - name: oracle-adb
          persistentVolumeClaim:
            claimName: oracle-adb
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-adb
  namespace: oracle
spec:
  type: LoadBalancer
  ports:
    - name: oraclenet
      port: 1521
      targetPort: 1521
    - name: oraclenet-mtls
      port: 1522
      targetPort: 1522
    - name: ords
      port: 8443
      targetPort: 8443
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    app: oracle-adb
